# Generated by Django 2.2.24 on 2021-11-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlbumApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='captureDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='capturedBy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='geolocation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
